//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models.Entities.CustomEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_USERModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_USERModel()
        {
            this.G_USER_BRANCH = new HashSet<G_USER_BRANCH>();
            this.G_USER_COMPANY = new HashSet<G_USER_COMPANY>();
            this.G_USER_LOG = new HashSet<G_USER_LOG>();
            this.G_USER_MODULE = new HashSet<G_USER_MODULE>();
            this.G_USER_SUB_SYSTEM = new HashSet<G_USER_SUB_SYSTEM>();
            this.G_USER_SYSTEM = new HashSet<G_USER_SYSTEM>();
        }
    
        public string USER_CODE { get; set; }
        public string USER_PASSWORD { get; set; }
        public bool USER_ACTIVE { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<int> CompCode { get; set; }
        public string REGION_CODE { get; set; }
        public Nullable<int> GRP_CODE { get; set; }
        public string USER_PASSWORD2 { get; set; }
        public string USER_PASSWORD3 { get; set; }
        public Nullable<System.DateTime> CHANGE_PASS_DATE { get; set; }
        public string MANUAL_VC { get; set; }
        public string MASTER_USER_CODE { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string DepartmentName { get; set; }
        public string JobTitle { get; set; }
        public Nullable<byte> USER_TYPE { get; set; }
        public string ManagedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_USER_BRANCH> G_USER_BRANCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_USER_COMPANY> G_USER_COMPANY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_USER_LOG> G_USER_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_USER_MODULE> G_USER_MODULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_USER_SUB_SYSTEM> G_USER_SUB_SYSTEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_USER_SYSTEM> G_USER_SYSTEM { get; set; }
    }
}
