//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_D_CalenderDays
    {
        public int CalenderDaysID { get; set; }
        public Nullable<int> CalenderID { get; set; }
        public Nullable<byte> DayOfWeek { get; set; }
        public Nullable<bool> WorkingDay { get; set; }
        public Nullable<decimal> WorkHours { get; set; }
    }
}
