//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_D_Labor
    {
        public int LaborID { get; set; }
        public Nullable<int> LaborClassId { get; set; }
        public Nullable<int> LaborCategoryId { get; set; }
        public string LaborCode { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> TotalAllow { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string CarPlateNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> BraCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> PhaseId { get; set; }
    }
}
