//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models
{
    using System;
    using System.Collections.Generic;

    public partial class P_G_Period
    {
        public int PeriodID { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<int> BraCode { get; set; }
        public Nullable<int> PeriodCode { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<bool> Closed { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpDateedAt { get; set; }
        public Nullable<decimal> ProdBudget { get; set; }
        public Nullable<decimal> MaterialCost { get; set; }
        public Nullable<decimal> LabourCost { get; set; }
        public Nullable<decimal> EquipmentCost { get; set; }
        public Nullable<decimal> ExpensesCost { get; set; }
        public Nullable<decimal> SubContractorCost { get; set; }
        public Nullable<decimal> ProductionOHCost { get; set; }
        public Nullable<decimal> OHCost { get; set; }
        public Nullable<decimal> ProdOHCost { get; set; }
        public Nullable<decimal> StdOHMaterial { get; set; }
        public Nullable<decimal> StdOHLabor { get; set; }
        public Nullable<decimal> StdOHEquip { get; set; }
        public Nullable<decimal> StdOHExpenses { get; set; }
        public Nullable<decimal> StdOHSubContractor { get; set; }
        public Nullable<decimal> StdProdOHMaterial { get; set; }
        public Nullable<decimal> StdProdOHLabor { get; set; }
        public Nullable<decimal> StdProdOHEquip { get; set; }
        public Nullable<decimal> StdProdOHExpenses { get; set; }
        public Nullable<decimal> StdProdOHSubContractor { get; set; }
        public Nullable<decimal> StdProfitMargin { get; set; }
    }
}
