//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_TR_EngScheduleLaborClass
    {
        public int ScheduleLaborClassId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<int> LaborCLassID { get; set; }
        public Nullable<decimal> RequiredNo { get; set; }
        public Nullable<decimal> RequiredHrs { get; set; }
        public Nullable<decimal> HourCost { get; set; }
    }
}
