//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models
{
    using System;
    using System.Collections.Generic;

    public partial class PQ_GetEngProjectItem
    {
        public int ProjectPhaseItemId { get; set; }
        public Nullable<int> ProjectPhaseId { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> OfferItemId { get; set; }
        public string LineCode { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<bool> IsFixedSystem { get; set; }
        public Nullable<decimal> ContrQty { get; set; }
        public Nullable<decimal> ItemQty { get; set; }
        public Nullable<decimal> ProdQty { get; set; }
        public Nullable<decimal> BilledQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> StdUnitPrice { get; set; }
        public Nullable<bool> IsOfferItem { get; set; }
        public Nullable<byte> ProductionType { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> EstimatedMaterial { get; set; }
        public Nullable<decimal> EstimatedLabor { get; set; }
        public Nullable<decimal> EstimatedEquip { get; set; }
        public Nullable<decimal> EstimatedProfit { get; set; }
        public Nullable<decimal> EstimatedOH { get; set; }
        public Nullable<decimal> EstimatedPOH { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> RelProjectPhaseItemId { get; set; }
        public Nullable<int> RelationType { get; set; }
        public Nullable<int> RelationDelay { get; set; }
        public string Phase_PhaseCode { get; set; }
        public string SlsITm_ItemCode { get; set; }
        public string SlsITm_DescA { get; set; }
        public string SlsITm_DescE { get; set; }
        public string Scp_ScopeCode { get; set; }
        public string Scp_DescA { get; set; }
        public string Scp_DescE { get; set; }
        public Nullable<int> ScopeID { get; set; }
        public string UomCode { get; set; }
    }
}
