//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models
{
    using System;
    using System.Collections.Generic;

    public partial class PQ_GetEngProjectPhase
    {
        public int ProjectPhaseId { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectPhaseCode { get; set; }
        public string DescA { get; set; }
        public string DescL { get; set; }
        public Nullable<int> OfferID { get; set; }
        public Nullable<int> OfferTrSerial { get; set; }
        public string CC_CODE { get; set; }
        public Nullable<int> OfferTrNo { get; set; }
        public Nullable<int> SiteEngineerId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsMaintenanceWork { get; set; }
        public Nullable<bool> IsBonusIncluded { get; set; }
        public Nullable<bool> ToBeInvoiced { get; set; }
        public Nullable<int> ScopeID { get; set; }
        public Nullable<int> CalenderId { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> EstimatedMaterial { get; set; }
        public Nullable<decimal> EstimatedLabor { get; set; }
        public Nullable<decimal> EstimatedEquip { get; set; }
        public Nullable<decimal> EstimatedProfit { get; set; }
        public Nullable<decimal> EstimatedOH { get; set; }
        public Nullable<decimal> EstimatedPOH { get; set; }
        public string Cal_Calendercode { get; set; }
        public string Cal_DescA { get; set; }
        public string Cal_DescE { get; set; }
        public Nullable<decimal> Cal_DailyWorkHours { get; set; }
        public string Scop_ScopeCode { get; set; }
        public string Scop_DescA { get; set; }
        public string Scop_DescE { get; set; }
        public string Eng_EngCode { get; set; }
        public string Eng_DescA { get; set; }
        public string Eng_DescE { get; set; }
        public string Status_DesecA { get; set; }
        public string Status_DescE { get; set; }
        public string EngProj_ProjectCode { get; set; }
        public string EngProj_DescA { get; set; }
        public string EngProj_DescL { get; set; }
        public Nullable<int> EngProj_CustomerId { get; set; }
        public string Cust_DescA { get; set; }
        public string Cust_DescE { get; set; }
        public Nullable<int> Cust_CustomerCode { get; set; }
        public Nullable<int> BraCode { get; set; }
        public Nullable<int> CompCode { get; set; }
        public Nullable<int> RelProjectPhaseId { get; set; }
        public Nullable<int> RelationType { get; set; }
        public Nullable<int> RelationDelay { get; set; }
        public Nullable<Boolean> ISPosted { get; set; }
    }
}
