
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models
{
    using System;
    using System.Collections.Generic;

    public partial class PQ_SrchEngProjectPhase
    {
        public string Proj_Code { get; set; }
        public string Proj_DescA { get; set; }
        public string Proj_DescE { get; set; }
        public Nullable<byte> Proj_Status { get; set; }
        public Nullable<int> Cust_Code { get; set; }
        public string Cust_DescA { get; set; }
        public string Cust_DescE { get; set; }
        public int ProjectID { get; set; }
        public int ProjectPhaseId { get; set; }
        public string Phase_Code { get; set; }
        public string Phase_DescA { get; set; }
        public string Phase_DescE { get; set; }
        public Nullable<int> ScopeID { get; set; }
        public Nullable<byte> Phase_Status { get; set; }
        public Nullable<int> BraCode { get; set; }
        public Nullable<int> CompCode { get; set; }
    }
}
