//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models
{
    using System;
    using System.Collections.Generic;

    public partial class P_D_SalesCustomer
    {
        public int CustomerID { get; set; }
        public Nullable<int> CustomerCategoryID { get; set; }
        public Nullable<int> CustomerCode { get; set; }
        public Nullable<bool> IsTemporary { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public string GLAccountCode { get; set; }
        public string ContactPerson { get; set; }
        public string ContactTel { get; set; }
        public string CustomerAddress { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CrNo { get; set; }
        public string ChamberNo { get; set; }
        public string VatNo { get; set; }
        public Nullable<byte> VatType { get; set; }
        public Nullable<int> SalesEngineerId { get; set; }
        public Nullable<int> BraCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CompCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string RefCode2 { get; set; }
        public string RefCode1 { get; set; }
        public Nullable<bool> ISPersonal { get; set; }
        public Nullable<bool> ISVatRegistered { get; set; }
        public string Address_postal { get; set; }
        public string Address_Province { get; set; }
        public string Address_Street { get; set; }
        public string Address_Str_Additional { get; set; }
        public string Address_BuildingNo { get; set; }
        public string Address_Build_Additional { get; set; }
        public string Address_City { get; set; }
        public string Address_District { get; set; }

    }
}
