//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_TR_SalesProductionDetail
    {
        public int ProductionDetailId { get; set; }
        public Nullable<int> ProductionId { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> ProjectPhaseItemId { get; set; }
        public Nullable<decimal> PrevProdQty { get; set; }
        public Nullable<decimal> ProdQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> BilledQty { get; set; }
        public Nullable<decimal> RejectedQty { get; set; }
        public string Remarks { get; set; }
    }
}
