//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_GETSalesItemSystemAct
    {
        public int ItemID { get; set; }
        public string ItemCode { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public Nullable<int> UomID { get; set; }
        public Nullable<decimal> MinUnitPrice { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> ParentItemID { get; set; }
        public int ScopeID { get; set; }
        public Nullable<int> ItemLevel { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDetail { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CompCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string SystemCode { get; set; }
        public string SysDescA { get; set; }
        public string SysDescE { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<decimal> CalcUnitPrice { get; set; }
        public Nullable<decimal> SysMinUnitPrice { get; set; }
        public Nullable<decimal> SysUnitPrice { get; set; }
        public int ItemsSystemId { get; set; }
        public Nullable<int> SysItemID { get; set; }
        public Nullable<int> SysCompCode { get; set; }
        public string UomCode { get; set; }
        public string UomDescA { get; set; }
        public string UomDescE { get; set; }
        public string ScopeCode { get; set; }
        public string ScopeDescA { get; set; }
        public string ScopeDescE { get; set; }
        public int ItemsSystemActivityId { get; set; }
        public Nullable<int> SysActItemSystemID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<decimal> ActQty { get; set; }
        public Nullable<bool> IsProdIncluded { get; set; }
        public Nullable<decimal> ProdPrc { get; set; }
        public string ActivityCode { get; set; }
        public string ActDescA { get; set; }
        public string ActDescE { get; set; }
        public string NAMEA { get; set; }
        public string puomcode { get; set; }
        public string puomdescA { get; set; }
        public string puomDescE { get; set; }
    }
}
