//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_GetSlsCustomer
    {
        public int CustomerID { get; set; }
        public Nullable<int> CustomerCategoryID { get; set; }
        public Nullable<int> CustomerCode { get; set; }
        public Nullable<bool> IsTemporary { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public string GLAccountCode { get; set; }
        public string ContactPerson { get; set; }
        public string ContactTel { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string CustomerAddress { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CrNo { get; set; }
        public string ChamberNo { get; set; }
        public string VatNo { get; set; }
        public Nullable<byte> VatType { get; set; }
        public int SalesEngineerId { get; set; }
        public Nullable<int> BraCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CompCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string custEng_code { get; set; }
        public string custeng_descA { get; set; }
        public string CustEng_descE { get; set; }
        public string CustomerCatCode { get; set; }
        public string CatDescA { get; set; }
        public string CatDescE { get; set; }
        public string ProjectCode { get; set; }
        public string Proj_descA { get; set; }
        public string Proj_descE { get; set; }
        public string CustomerAccCode { get; set; }
        public string CustomerTel { get; set; }
        public string Customermobile { get; set; }
        public string CustomerContact { get; set; }
        public string Proj_remarks { get; set; }
        public Nullable<int> ProjBraCode { get; set; }
        public string ProjEngCode { get; set; }
    }
}
