//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY
    {
        public int COMP_CODE { get; set; }
        public int BRA_CODE { get; set; }
        public string ACT_CODE { get; set; }
        public string DESCA { get; set; }
        public string DESCE { get; set; }
        public string UOM_CODE { get; set; }
        public Nullable<decimal> LAB_PROD_RATE { get; set; }
        public Nullable<decimal> HR_PROD { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public string PARENT_ACT_CODE { get; set; }
        public Nullable<short> ACT_LEVEL { get; set; }
        public Nullable<bool> DETAIL { get; set; }
        public string REMARKS { get; set; }
    }
}
