//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_CONTROL
    {
        public int COMP_CODE { get; set; }
        public Nullable<int> FIN_YEAR { get; set; }
        public Nullable<short> GEN_STATUS { get; set; }
        public Nullable<short> ACC_STATUS { get; set; }
        public Nullable<short> INV_STATUS { get; set; }
        public Nullable<short> PER_STATUS { get; set; }
        public Nullable<short> CLN_STATUS { get; set; }
        public Nullable<short> PRJ_STATUS { get; set; }
        public Nullable<bool> CLOSE_ACC_PERIOD { get; set; }
        public string BACKUP_DB { get; set; }
        public Nullable<int> BACKUP_COPIES { get; set; }
        public string SERVER_PATH { get; set; }
        public Nullable<bool> SYS_CLOSED { get; set; }
        public Nullable<bool> ACC_FINAL_CLOSED { get; set; }
        public Nullable<System.DateTime> FIRST_DATE { get; set; }
        public Nullable<System.DateTime> LAST_DATE { get; set; }
    }
}
