//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_ReportWebSetting
    {
        public int ReportSettingID { get; set; }
        public string SystemCode { get; set; }
        public string SubSystemCode { get; set; }
        public string ReportID { get; set; }
        public string NameA { get; set; }
        public string NameE { get; set; }
        public Nullable<int> COMP_CODE { get; set; }
        public Nullable<int> BRA_Code { get; set; }
        public string USER_CODE { get; set; }
        public string ReportDesignNameEn { get; set; }
        public string ReportDesignNameAr { get; set; }
        public string ReportDataSouce { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public Nullable<int> RightMargin { get; set; }
        public Nullable<int> LeftMargin { get; set; }
        public Nullable<int> TopMargin { get; set; }
        public Nullable<int> BottomMargin { get; set; }
        public Nullable<byte> Orientation { get; set; }
        public Nullable<byte> PageSize { get; set; }
        public string PrinterName { get; set; }
        public Nullable<byte> OutputTypeNo { get; set; }
        public string OutputType { get; set; }
    }
}
