//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_SMSControl
    {
        public int SMSControlId { get; set; }
        public string ViewName { get; set; }
        public string IDField { get; set; }
        public string Condition { get; set; }
        public Nullable<int> SMSID { get; set; }
        public string SendToField { get; set; }
    }
}
