//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GQ_UserFavorite
    {
        public string MODULE_CODE { get; set; }
        public string MODULE_DESCE { get; set; }
        public string MODULE_DESCA { get; set; }
        public Nullable<int> OPTIONORDER { get; set; }
        public string SYSTEM_CODE { get; set; }
        public string SUB_SYSTEM_CODE { get; set; }
        public string USER_CODE { get; set; }
    }
}
