//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_SrchItem
    {
        public int ItemID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> CompCode { get; set; }
        public string DescA { get; set; }
        public string DescL { get; set; }
        public Nullable<decimal> GlobalCost { get; set; }
        public string UomCode { get; set; }
        public string Unit_descA { get; set; }
        public string Unit_descE { get; set; }
        public string CatCode { get; set; }
        public string Cat_DescA { get; set; }
        public string Cat_DescE { get; set; }
    }
}
