//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_D_SubCandidate
    {
        public int SubContractorID { get; set; }
        public Nullable<int> CandidateCode { get; set; }
        public Nullable<int> SubContractorCode { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public string ContactPerson { get; set; }
        public string ContactTel { get; set; }
        public string SubContractorAddress { get; set; }
        public string Specialty { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string CrNo { get; set; }
        public string ChamberNo { get; set; }
        public string VatNo { get; set; }
        public Nullable<byte> VatType { get; set; }
        public Nullable<decimal> ContractLimit { get; set; }
        public Nullable<int> BraCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CompCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
