//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_D_SalesEgineer
    {
        public int SalesEngineerId { get; set; }
        public Nullable<int> SalesEngCategoryId { get; set; }
        public string EngCode { get; set; }
        public string DeacA { get; set; }
        public string DescE { get; set; }
        public string Speciality { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> TotalAllow { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public string CarPlateNo { get; set; }
        public Nullable<int> BraCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CompCode { get; set; }
    }
}
