//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_D_ActivityIMaterial
    {
        public int ActivityMaterialID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> ProdQty { get; set; }
        public Nullable<decimal> WastPrc { get; set; }
        public Nullable<decimal> WastQty { get; set; }
        public Nullable<decimal> ReqQty { get; set; }
    }
}
