//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_D_SubCandidateScope
    {
        public int SubCandidateScopeId { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<int> ScopeId { get; set; }
        public Nullable<System.DateTime> ApplayDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<decimal> ContractLimit { get; set; }
        public string Remarks { get; set; }
    }
}
