//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_G_Budget
    {
        public int BudjetID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> PeriodCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> SiteEngineerId { get; set; }
        public Nullable<int> ProjectPhaseItemActivId { get; set; }
        public Nullable<decimal> BudgetQty { get; set; }
        public Nullable<decimal> ActualQty { get; set; }
    }
}
