//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_G_Region
    {
        public int COMP_CODE { get; set; }
        public int REGION_CODE { get; set; }
        public string DESCA { get; set; }
        public string DESCE { get; set; }
        public string REMARKS { get; set; }
    }
}
