//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_TR_SalesInvoiceProd
    {
        public int InvoiceProdId { get; set; }
        public Nullable<int> InvoiceDetailId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> ProductionDetailId { get; set; }
        public Nullable<int> ProductionId { get; set; }
        public Nullable<int> ProjectPhaseItemId { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> InvQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> BilledQty { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> ToBillQty { get; set; }
    }
}
