//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Tr_SalesBonusDetail
    {
        public int SalesBonusDetailId { get; set; }
        public int SalesBonusId { get; set; }
        public Nullable<int> SalesEngineerId { get; set; }
        public Nullable<int> SalesEngCategoryId { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> OpenBasket { get; set; }
        public Nullable<decimal> OpenSales { get; set; }
        public Nullable<decimal> CurrentSales { get; set; }
        public Nullable<decimal> AddToBusket { get; set; }
        public Nullable<decimal> CurrentBasket { get; set; }
        public Nullable<decimal> CurrentInvoices { get; set; }
        public Nullable<decimal> BonusAmount { get; set; }
    }
}
