//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Tr_SalesActivtyPriceDetail
    {
        public int ActivityPriceDetailId { get; set; }
        public Nullable<int> ActivityPriceId { get; set; }
        public int ActivityID { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
        public Nullable<decimal> MatCost { get; set; }
        public Nullable<decimal> LaborCost { get; set; }
        public Nullable<decimal> EquipCost { get; set; }
        public Nullable<decimal> POHCost { get; set; }
        public Nullable<decimal> OHCost { get; set; }
        public Nullable<decimal> Profit { get; set; }
    }
}
