//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_TR_EngVariationActivity
    {
        public int VariationActivId { get; set; }
        public Nullable<int> ProjectPhaseId { get; set; }
        public Nullable<int> VariationItemId { get; set; }
        public Nullable<int> VariationId { get; set; }
        public Nullable<int> ProjectPhaseItemActivId { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<decimal> Old_ActivQty { get; set; }
        public Nullable<decimal> ActivQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> StdUnitPrice { get; set; }
        public Nullable<decimal> OldProductionPrc { get; set; }
        public Nullable<decimal> ProductionPrc { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> EstimatedMaterial { get; set; }
        public Nullable<decimal> EstimatedLabor { get; set; }
        public Nullable<decimal> EstimatedEquip { get; set; }
        public Nullable<decimal> EstimatedProfit { get; set; }
        public Nullable<decimal> OldEffItemQty { get; set; }
        public Nullable<decimal> NewEffItemQty { get; set; }
        public Nullable<decimal> TotProdQty { get; set; }
        public Nullable<decimal> UnderProdQty { get; set; }
    }
}
