//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Tr_SalesOfferStageItem
    {
        public int OfferItemId { get; set; }
        public Nullable<int> OfferStageId { get; set; }
        public Nullable<int> OfferID { get; set; }
        public string LineCode { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemCode { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public string TechDescA { get; set; }
        public string TechDescE { get; set; }
        public Nullable<int> UomID { get; set; }
        public Nullable<bool> IsFixedSystem { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> StdUnitPrice { get; set; }
        public Nullable<decimal> MinUnitPrice { get; set; }
        public Nullable<bool> IsOfferItem { get; set; }
        public Nullable<byte> ProductionType { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> EstimatedMaterial { get; set; }
        public Nullable<decimal> EstimatedLabor { get; set; }
        public Nullable<decimal> EstimatedEquip { get; set; }
        public Nullable<decimal> EstimatedProfit { get; set; }
        public Nullable<decimal> EstimatedOH { get; set; }
        public Nullable<decimal> EstimatedPOH { get; set; }
    }
}
