//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    
    public partial class PProc_Eng_BudgetEngineerActiv_Result1
    {
        public Nullable<int> ProjectPhaseItemActivId { get; set; }
        public Nullable<int> ProjectPhaseId { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public int budjetid { get; set; }
        public decimal BudVal { get; set; }
        public Nullable<decimal> ActualQty { get; set; }
        public Nullable<decimal> BudgetQty { get; set; }
        public decimal ActVal { get; set; }
        public Nullable<decimal> ActivQty { get; set; }
        public decimal ActTotalValue { get; set; }
        public string ActivityCode { get; set; }
        public string DESCE { get; set; }
        public string DescA { get; set; }
        public Nullable<int> PeriodCode { get; set; }
        public string projectphasecode { get; set; }
        public decimal ActYTD { get; set; }
        public decimal BudYTD { get; set; }
        public decimal PM_ActualQty { get; set; }
        public decimal PM_BudgetQty { get; set; }
    }
}
