//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    
    public partial class PProc_Prnt_def_SalesEngineer_Result1
    {
        public Nullable<int> Comp { get; set; }
        public string CompNameA { get; set; }
        public string CompNameE { get; set; }
        public string BraNameA { get; set; }
        public string BraNameE { get; set; }
        public string LoginUser { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string Par_active { get; set; }
        public string Par_branchnameA { get; set; }
        public string Par_branchnameE { get; set; }
        public string EngCode { get; set; }
        public string DeacA { get; set; }
        public string DescE { get; set; }
        public string Tel1 { get; set; }
        public string Mobile { get; set; }
        public string CarPlateNo { get; set; }
        public Nullable<int> BraCode { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> TotalAllow { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string cat_descA { get; set; }
        public string cat_descE { get; set; }
    }
}
