//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_Calc_ActivityLocalCost
    {
        public int ActivityID { get; set; }
        public int BraCode { get; set; }
        public decimal UnitLab { get; set; }
        public decimal UnitMat { get; set; }
        public decimal UnitEquip { get; set; }
        public Nullable<decimal> UnitOH { get; set; }
        public Nullable<decimal> UnitPOH { get; set; }
        public Nullable<decimal> UnitProfit { get; set; }
    }
}
