//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_GetSlsOfferPayment
    {
        public int OfferPaymentId { get; set; }
        public Nullable<int> OfferID { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string pay_PaymentCode { get; set; }
        public string Pay_DescA { get; set; }
        public string Pay_DescE { get; set; }
    }
}
