//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_GetEngproductionActivity
    {
        public int ProductionActivId { get; set; }
        public Nullable<int> ProductionId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<int> ScheduleActivId { get; set; }
        public Nullable<decimal> FinishQty { get; set; }
        public Nullable<decimal> ProdBeforeQty { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> ProjectPhaseItemActivId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string Act_Code { get; set; }
        public string Act_DescA { get; set; }
        public string Act_DescE { get; set; }
        public string Itm_Code { get; set; }
        public string Itm_DescA { get; set; }
        public string Itm_DescE { get; set; }
        public Nullable<decimal> Act_HourProduction { get; set; }
        public Nullable<decimal> ProjAct_ActivQty { get; set; }
        public Nullable<bool> ProjAct_ProductionIncluded { get; set; }
        public Nullable<decimal> ProjAct_ProductionPrc { get; set; }
        public Nullable<decimal> schAct_SchedQty { get; set; }
        public Nullable<decimal> RemainQty { get; set; }
    }
}
