//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_GetEngSubContract
    {
        public int SubContractId { get; set; }
        public Nullable<int> TrNo { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public Nullable<int> SubContractorID { get; set; }
        public Nullable<int> ScopeID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ProjectPhaseId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<bool> ISMaterialIncluded { get; set; }
        public Nullable<bool> ISFlexQty { get; set; }
        public Nullable<bool> IsBlank { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Terms { get; set; }
        public string Technical { get; set; }
        public string Penalty { get; set; }
        public string MaterialRemarks { get; set; }
        public string EquipmentRemarks { get; set; }
        public string LaborRemarks { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> WarrantyPeriod { get; set; }
        public Nullable<decimal> DownpaymentPrc { get; set; }
        public Nullable<decimal> WarranlyPrc { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BraCode { get; set; }
        public Nullable<int> CompCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> IsApproved { get; set; }
        public Nullable<int> IsClosed { get; set; }
        public Nullable<int> Sc_Code { get; set; }
        public string Sc_DescA { get; set; }
        public string Sc_DescE { get; set; }
        public string Scope_Code { get; set; }
        public string Scope_DescA { get; set; }
        public string Scope_DescE { get; set; }
        public string Phase_Code { get; set; }
        public string Phase_DescA { get; set; }
        public string Phase_DescE { get; set; }
        public string Proj_Code { get; set; }
        public string Proj_DescA { get; set; }
        public string Proj_DescE { get; set; }
        public int Tot_FinishSo { get; set; }
        public int Tot_IssueSo { get; set; }
        public Nullable<int> Tot_OpenSo { get; set; }
        public Nullable<int> SiteEngineerId { get; set; }
        public Nullable<decimal> Sc_Limit { get; set; }
        public Nullable<byte> VatType { get; set; }
    }
}
