//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_GetActivityMaterialClass
    {
        public int ActivityMaterialID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> ProdQty { get; set; }
        public Nullable<decimal> WastPrc { get; set; }
        public Nullable<decimal> WastQty { get; set; }
        public Nullable<decimal> ReqQty { get; set; }
        public string ItemCode { get; set; }
        public string DescA { get; set; }
        public string DescL { get; set; }
        public string UomCode { get; set; }
        public string Unit_descA { get; set; }
        public string Unit_descE { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
