//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_GetSalesFillInvoiceProd
    {
        public Nullable<int> Prod_TrNo { get; set; }
        public Nullable<System.DateTime> Prod_TrDate { get; set; }
        public Nullable<int> Prod_ProjectID { get; set; }
        public Nullable<System.DateTime> Prod_FromDate { get; set; }
        public Nullable<System.DateTime> Prod_ToDate { get; set; }
        public Nullable<bool> Prod_IsFinal { get; set; }
        public string Prod_RefCode { get; set; }
        public string Prod_WorkDiscription { get; set; }
        public string Itm_ItemCode { get; set; }
        public string Itm_DescA { get; set; }
        public string Itm_DescE { get; set; }
        public Nullable<decimal> ProdQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> BilledQty { get; set; }
        public Nullable<decimal> ToBillQty { get; set; }
        public string Remarks { get; set; }
        public int Prod_ProductionId { get; set; }
        public int ProductionDetailId { get; set; }
        public Nullable<int> ProductionId { get; set; }
        public Nullable<int> ProjectPhaseItemId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string LineCode { get; set; }
    }
}
