//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_GetSalesOffer
    {
        public int OfferID { get; set; }
        public Nullable<int> TrNo { get; set; }
        public Nullable<int> TrSerial { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public string RefCode { get; set; }
        public string DescA { get; set; }
        public string DescL { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<bool> IsMaintenanceWork { get; set; }
        public Nullable<bool> IsMainCustomerPay { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<decimal> ProjArea { get; set; }
        public string ProjAddress { get; set; }
        public string ProjTechnicalSpecs { get; set; }
        public string ProjectTermsCond { get; set; }
        public string ProjectPenalties { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerPONo { get; set; }
        public Nullable<int> SalesEngineerId { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BraCode { get; set; }
        public Nullable<int> CompCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> WorkStartId { get; set; }
        public Nullable<bool> IsNewProject { get; set; }
        public Nullable<int> ProjectBranch { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<int> PhaseID { get; set; }
        public string PhaseCode { get; set; }
        public string ContractCode { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<int> ContractPeriod { get; set; }
        public Nullable<decimal> ContractPrice { get; set; }
        public Nullable<decimal> ContractNetPrice { get; set; }
        public Nullable<decimal> DiscountPrc { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string ContractWarantyPrd { get; set; }
        public Nullable<byte> PaymentMethod { get; set; }
        public Nullable<decimal> DownPaymentPrc { get; set; }
        public Nullable<decimal> DownPaymentAmount { get; set; }
        public Nullable<decimal> WarrntyPaymentPrc { get; set; }
        public Nullable<decimal> WarrntyPaymentAmount { get; set; }
        public Nullable<decimal> OHMaterialPrc { get; set; }
        public Nullable<decimal> OHLaborPrc { get; set; }
        public Nullable<decimal> OHEquipPrc { get; set; }
        public Nullable<decimal> ProdOHMaterialPrc { get; set; }
        public Nullable<decimal> ProdOHLaborPrc { get; set; }
        public Nullable<decimal> ProdOHEquipPrc { get; set; }
        public Nullable<decimal> ProfitMarginPrc { get; set; }
        public Nullable<decimal> EstimatedMaterial { get; set; }
        public Nullable<decimal> EstimatedLabor { get; set; }
        public Nullable<decimal> EstimatedEquip { get; set; }
        public Nullable<decimal> EstimatedProfit { get; set; }
        public string Loc_LocCode { get; set; }
        public string Loc_DescA { get; set; }
        public string loc_DescE { get; set; }
        public string eng_EngCode { get; set; }
        public string Eng_DescA { get; set; }
        public string Eng_DescE { get; set; }
        public Nullable<int> cus_CustomerCode { get; set; }
        public Nullable<bool> cus_IsTemporary { get; set; }
        public string cus_DescA { get; set; }
        public string Cus_DescE { get; set; }
        public Nullable<decimal> EstimatedOH { get; set; }
        public Nullable<decimal> EstimatedPOH { get; set; }
        public Nullable<decimal> VatPrc { get; set; }
        public Nullable<decimal> WaranteePrd { get; set; }
    }
}
