//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_GetSlsOfferBilling
    {
        public int OfferBillingId { get; set; }
        public Nullable<int> OfferID { get; set; }
        public Nullable<int> Serial { get; set; }
        public string PayDescA { get; set; }
        public string PayDescE { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> OfferItemId { get; set; }
        public string ProductionPrc { get; set; }
        public Nullable<decimal> DuePrc { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<int> OffStage_OfferItemId { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public string ItemCode { get; set; }
    }
}
