//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_GetSalesItemSystems
    {
        public int ItemSystemID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> SystemID { get; set; }
        public Nullable<decimal> StdPrice { get; set; }
        public Nullable<decimal> MinUnitPrice { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ScopeID { get; set; }
        public string SystemCode { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public string SysRemarks { get; set; }
    }
}
