//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_GetActivityLaborClass
    {
        public string ClassCode { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public int ActivityLaborClassID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> LaborClassId { get; set; }
        public Nullable<decimal> NoOfLabors { get; set; }
        public Nullable<decimal> HourCost { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
