//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_GetProjCustomer
    {
        public int CustomerID { get; set; }
        public Nullable<int> CustomerCategoryID { get; set; }
        public Nullable<int> CustomerCode { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public Nullable<bool> IsTemporary { get; set; }
        public Nullable<int> BraCode { get; set; }
        public Nullable<int> SalesEngineerId { get; set; }
        public int ProjectID { get; set; }
        public string ProjectCode { get; set; }
        public string Expr1 { get; set; }
        public string DescL { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<int> Expr3 { get; set; }
    }
}
