//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_GetEngWorkSchdule
    {
        public int ScheduleId { get; set; }
        public Nullable<int> TrNo { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public Nullable<int> ProjectPhaseId { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<int> CalenderId { get; set; }
        public string WorkDescr { get; set; }
        public Nullable<int> RequestMaterialId { get; set; }
        public Nullable<int> RequestLabourId { get; set; }
        public Nullable<int> RequestEquipmentId { get; set; }
        public Nullable<decimal> WorkHours { get; set; }
        public Nullable<bool> IsOverTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BraCode { get; set; }
        public Nullable<int> CompCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string Prj_ProjectCode { get; set; }
        public string Prj_DescA { get; set; }
        public string Prj_DescE { get; set; }
        public Nullable<byte> Prj_Status { get; set; }
        public string Phase_ProjectPhaseCode { get; set; }
        public string Phase_DescA { get; set; }
        public string Phase_DescE { get; set; }
        public string Phase_CCCode { get; set; }
        public Nullable<byte> Phase_Status { get; set; }
        public string Cal_calenderCode { get; set; }
        public string Cal_DescA { get; set; }
        public string Cal_DescE { get; set; }
        public Nullable<int> RLab_TrNo { get; set; }
        public Nullable<int> REq_TrNo { get; set; }
        public Nullable<int> RMat_TrNo { get; set; }
        public Nullable<decimal> CalHours { get; set; }
        public Nullable<decimal> OTHours { get; set; }
    }
}
