//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_SrcSchdule
    {
        public int ScheduleId { get; set; }
        public Nullable<int> TrNo { get; set; }
        public string WorkDescr { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Prj_ProjectCode { get; set; }
        public string Prj_DescE { get; set; }
        public string Prj_DescA { get; set; }
        public Nullable<int> ProjectPhaseId { get; set; }
        public string Phase_ProjectPhaseCode { get; set; }
        public string Phase_DescA { get; set; }
        public string Phase_DescE { get; set; }
        public Nullable<int> SiteEngineerId { get; set; }
        public string Eng_EngCode { get; set; }
        public string Eng_DescA { get; set; }
        public string Eng_DescE { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> BraCode { get; set; }
        public Nullable<int> CompCode { get; set; }
    }
}
