//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ApiService.Models
{
    using System;
    using System.Collections.Generic;

    public partial class P_tol_GetMessage
    {
        public int comp { get; set; }
        public int TrTyp { get; set; }
        public int memid { get; set; }
        public int trid { get; set; }
        public int MsgType { get; set; }
        public string HdMsg { get; set; }
        public string DetMsg { get; set; }

    }
}
