//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_COMPANY
    {
        public int COMP_CODE { get; set; }
        public string MOI_ID { get; set; }
        public string CRT_NO { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string GMName { get; set; }
        public string HRResponsible { get; set; }
        public string FinanceResponsible { get; set; }
        public string SalesManager { get; set; }
        public string CUSTOM1 { get; set; }
        public string CUSTOM2 { get; set; }
        public string CUSTOM3 { get; set; }
        public string CUSTOM4 { get; set; }
        public string CUSTOM5 { get; set; }
        public Nullable<bool> CUSTOMFLAG1 { get; set; }
        public Nullable<bool> CUSTOMFLAG2 { get; set; }
        public Nullable<decimal> CUSTOMNUM1 { get; set; }
        public Nullable<decimal> CUSTOMNUM2 { get; set; }
        public Nullable<System.DateTime> CUSTOMDATE { get; set; }
    }
}
