//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_USER_MODULE
    {
        public string USER_CODE { get; set; }
        public string SYSTEM_CODE { get; set; }
        public string SUB_SYSTEM_CODE { get; set; }
        public string MODULE_CODE { get; set; }
        public bool EXECUTE { get; set; }
        public bool CREATE { get; set; }
        public bool EDIT { get; set; }
        public bool DELETE { get; set; }
        public bool PRINT { get; set; }
        public bool VIEW { get; set; }
        public bool CUSTOM1 { get; set; }
        public bool CUSTOM2 { get; set; }
        public bool CUSTOM3 { get; set; }
        public Nullable<bool> CUSTOM4 { get; set; }
        public Nullable<bool> CUSTOM5 { get; set; }
        public Nullable<bool> CUSTOM6 { get; set; }
        public Nullable<bool> CUSTOM7 { get; set; }
        public Nullable<bool> CUSTOM8 { get; set; }
        public Nullable<bool> CUSTOM9 { get; set; }
        public Nullable<bool> ViewImages { get; set; }
        public Nullable<bool> EditImages { get; set; }
    }
}
