//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.ServiceConnector.Models
{
    using System;
    using System.Collections.Generic;

    public partial class P_Control
    {
        public int CompCode { get; set; }
        public int BraCode { get; set; }
        public Nullable<bool> LinkToAccount { get; set; }
        public Nullable<bool> MonthlyClose { get; set; }
        public string ScanPath { get; set; }
        public Nullable<decimal> MaterialWastPrc { get; set; }
        public Nullable<int> UserTimeZoneUTCDiff { get; set; }
        public Nullable<int> ServerTimeZoneUTCDiff { get; set; }
        public Nullable<int> VATNumberLength { get; set; }
        public Nullable<int> CrNumberLength { get; set; }
        public Nullable<decimal> AverageLaborCost { get; set; }
        public Nullable<decimal> StdOHMaterial { get; set; }
        public Nullable<decimal> StdOHLabor { get; set; }
        public Nullable<decimal> StdOHEquip { get; set; }
        public Nullable<decimal> StdOHSubContractor { get; set; }
        public Nullable<decimal> StdProdOHMaterial { get; set; }
        public Nullable<decimal> StdProdOHLabor { get; set; }
        public Nullable<decimal> StdProdOHEquip { get; set; }
        public Nullable<decimal> StdProdOHSubContractor { get; set; }
        public Nullable<decimal> StdProfitMargin { get; set; }
        public Nullable<bool> IsNotificaitonActive { get; set; }
        public Nullable<bool> IsDashboardActive { get; set; }
        public Nullable<int> NotePeriodinSec { get; set; }
        public Nullable<int> DashBoardPeriodinSec { get; set; }
        public Nullable<int> MaxImagesize { get; set; }
        public string ImgPath { get; set; }
        public Nullable<decimal> VatPrc { get; set; }

    }
}
